default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: hammadali
  password: password
  host: localhost
development:
  <<: *default
  database: youtube_development
  sslmode: disable
test:
  <<: *default
  database: youtube_test
  sslmode: disable
production:
  <<: *default
  database: youtube_production